version: "3.8"

name: pytasks-test

services:
  postgres-test:
    image: postgres:15-alpine
    container_name: pytasks-postgres-test
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=pytasks_test
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pytasks_test"]
      interval: 2s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  postgres_test_data:
