# Main Docker Compose configuration for running the complete stack
version: '3.8'

name: pytasks

services:
  postgres:
    image: postgres:15-alpine
    container_name: pytasks-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=pytasks
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pytasks-api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/pytasks
      - ENVIRONMENT=prod
      - DEBUG=false
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
