# Development environment - Only PostgreSQL for local API development
version: "3.8"

name: pytasks-dev

services:
  postgres:
    image: postgres:15-alpine
    container_name: pytasks-postgres-dev
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=pytasks
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
